version: "3.2"

services:
  app:
    platform: linux/amd64
    image: "matterlabs/block-explorer-app:latest"
    ports:
      - '3010:3010'
    depends_on:
      - api
    restart: unless-stopped

  worker:
    platform: linux/amd64
    image: "matterlabs/block-explorer-worker:latest"
    environment:
      - PORT=3001
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - DATABASE_HOST=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=block-explorer
      - BLOCKCHAIN_RPC_URL=http://zksync:3050
      - DATA_FETCHER_URL=http://data-fetcher:3040
      - BATCHES_PROCESSING_POLLING_INTERVAL=1000
    ports:
      - '3001:3001'
      - '9229:9229'
      - '9230:9230'
    depends_on:
      zksync:
        condition: service_healthy
    restart: unless-stopped

  data-fetcher:
    platform: linux/amd64
    image: "matterlabs/block-explorer-data-fetcher:latest"
    environment:
      - PORT=3040
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - BLOCKCHAIN_RPC_URL=http://zksync:3050
    ports:
      - '3040:3040'
    depends_on:
      zksync:
        condition: service_healthy
    restart: unless-stopped

  api:
    platform: linux/amd64
    image: "matterlabs/block-explorer-api:latest"
    environment:
      - PORT=3020
      - METRICS_PORT=3005
      - LOG_LEVEL=verbose
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/block-explorer
    ports:
      - '3020:3020'
    depends_on:
      - worker
    restart: unless-stopped

  postgres:
    image: "postgres:14"
    logging:
      driver: none
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=block-explorer

  geth:
    image: "matterlabs/geth:latest"
    logging:
      driver: none
    ports:
      - "8545:8545"
      - "8546:8546"
    volumes:
      - geth:/var/lib/geth/data

  zksync:
    stdin_open: true
    tty: true
    image: matterlabs/local-node:latest2.0
    depends_on:
      postgres:
        condition: service_healthy
      geth:
        condition: service_started
    ports:
      - "3050:3050" # JSON RPC HTTP port
      - "3051:3051" # JSON RPC WS port
    volumes:
      # Configs folder bind
      - zksync-config:/etc/env/
      # Storage folder bind
      - zksync-data:/var/lib/zksync/data
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/zksync_local
      - ETH_CLIENT_WEB3_URL=http://geth:8545
    healthcheck:
      test: "curl -H \"Content-Type: application/json\" -X POST --data '{\"jsonrpc\":\"2.0\",\"method\":\"web3_clientVersion\",\"params\":[],\"id\":67}' 127.0.0.1:3050 || exit 1"
      interval: 5s
      timeout: 5s
      retries: 120
    restart: unless-stopped

volumes:
  geth:
  postgres:
  zksync-config:
  zksync-data: